### ISSUE TITLE
with_retries 在调用时报错

### ISSUE THREAD

**Issue by wenlingang** [seandong/lark-ruby-sdk#23]
@cod7ce  master 分支在调用接口时报错：

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/24770072/221400045-9e3ae98d-2796-4151-85af-17216037ff27.png">

**Comment by cod7ce** [comment]
已修复，增加了 retries 的依赖：https://github.com/seandong/lark-ruby-sdk/pull/24
